FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

# Can get rid of this since the docker-compose file
# does map the source code to the /app directory
# but you can keep it as a reference or reminder
COPY . .

CMD ["npm", "run", "start"]